apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elk-kibana
  namespace: elk
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: es-elk
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 2Gi
              cpu: 2
